Total Users = COUNTROWS(FactScores)
Actual Conversions = SUM(FactScores[Converted])
Baseline Conversion Rate = DIVIDE([Actual Conversions], [Total Users])
Expected Conversions = SUM(FactScores[Expected Conversion])
Average T1 Score = AVERAGE(FactScores[T1 Score])
Average T0 Score = AVERAGE(FactScores[T0 Score])
Users With Calls = CALCULATE([Total Users], FactScores[Has Calls] = 1)
Call Join Rate = DIVIDE([Users With Calls], [Total Users])
Users With Answered Calls = CALCULATE([Total Users], FactScores[Has Answered Call] = 1)
Very High Priority Users = CALCULATE([Total Users], FactScores[Priority Band] = "Very High")
Converted Top 100 = CALCULATE([Actual Conversions], FactScores[T1 Rank] <= 100)
Precision @ 100 = DIVIDE([Converted Top 100], 100)
Converted Top 500 = CALCULATE([Actual Conversions], FactScores[T1 Rank] <= 500)
Precision @ 500 = DIVIDE([Converted Top 500], 500)
Converted Top 1000 = CALCULATE([Actual Conversions], FactScores[T1 Rank] <= 1000)
Precision @ 1000 = DIVIDE([Converted Top 1000], 1000)
Recall @ 1000 = DIVIDE([Converted Top 1000], [Actual Conversions])
Top Decile Conversions = CALCULATE([Actual Conversions], FactScores[T1 Model Decile] = 10)
Top Decile Users = CALCULATE([Total Users], FactScores[T1 Model Decile] = 10)
Top Decile Conversion Rate = DIVIDE([Top Decile Conversions], [Top Decile Users])
Top Decile Lift = DIVIDE([Top Decile Conversion Rate], [Baseline Conversion Rate])
